### ISSUE TITLE
How to get the observation encoding code?

### ISSUE THREAD

**Issue by 1576012404** [SestoAle/DeepCrawl#1]
How to get the observation encoding code?
The final branch takes as input an array of 11 discrete values containing information about the agent and the player.i want to know how to transform the 11 discrete values to an array as i print like this:
'stats': array([ 7., 21., 24., 29., 30., 41., 51., 71., 75., 77., 80.])

how to encoding when i get the value of HP potion,weapon buff ? or where is the code?

**Comment by SestoAle** [comment]
Hi!

If you want to change the observations taken by the agent in the game, you can modify the ```CollectObservation()``` method in here: https://github.com/SestoAle/DeepCrawl/blob/78740787437742f1b3801c7a4226f5fcc690ddd1/DeepCrawl-Unity/Assets/Scripts/ML/Agents/BaseAgent.cs#L79

Otherwise, if you want to modify the structure of the observations, you can directly modify the python method ```get_input_observation()``` in here: https://github.com/SestoAle/DeepCrawl/blob/78740787437742f1b3801c7a4226f5fcc690ddd1/python-rl/unity_env_wrapper.py#L41
